<?php
// Liste des matchs avec des couleurs pour chaque équipe
$matches = [
    [
        'sport' => 'football',
        'equipe1' => ['name' => 'Paris Saint-Germain', 'color' => '#004170'],
        'equipe2' => ['name' => 'Olympique de Marseille', 'color' => '#0083ca'],
        'score' => '4-0',
        'resume' => 'Un match spectaculaire avec un doublé de Mbappé et une domination totale du PSG.',
        'is_active' => true,
    ],
    [
        'sport' => 'football',
        'equipe1' => ['name' => 'Lyon', 'color' => '#DA291C'],
        'equipe2' => ['name' => 'Monaco', 'color' => '#FFCD00'],
        'score' => '2-2',
        'resume' => 'Une rencontre équilibrée où Lacazette a marqué un but crucial pour Lyon à la 89e minute.',
        'is_active' => true,
    ],
    [
        'sport' => 'football',
        'equipe1' => ['name' => 'Lens', 'color' => '#FFD700'],
        'equipe2' => ['name' => 'Lille', 'color' => '#D40000'],
        'score' => '1-0',
        'resume' => 'Une victoire serrée pour Lens grâce à un but de Fofana à la 75e minute.',
        'is_active' => true,
    ],
    [
        'sport' => 'football',
        'equipe1' => ['name' => 'Rennes', 'color' => '#CE1126'],
        'equipe2' => ['name' => 'Nice', 'color' => '#ED1C24'],
        'score' => '0-3',
        'resume' => 'Nice a surpris Rennes avec une défense solide et trois contre-attaques fulgurantes.',
        'is_active' => false,
    ],
    [
        'sport' => 'football',
        'equipe1' => ['name' => 'Paris Saint-Germain', 'color' => '#004170'],
        'equipe2' => ['name' => 'Olympique de Marseille', 'color' => '#0083ca'],
        'score' => '0-4',
        'resume' => 'Un match spectaculaire avec une domination totale de l\'OM.',
        'is_active' => true,
    ],
    [
        'sport' => 'football',
        'equipe1' => ['name' => 'Lyon', 'color' => '#DA291C'],
        'equipe2' => ['name' => 'Monaco', 'color' => '#FFCD00'],
        'score' => '2-2',
        'resume' => 'Une rencontre équilibrée où Lacazette a marqué un but crucial pour Lyon à la 89e minute.',
        'is_active' => true,
    ],
    [
        'sport' => 'football',
        'equipe1' => ['name' => 'Lens', 'color' => '#FFD700'],
        'equipe2' => ['name' => 'Lille', 'color' => '#D40000'],
        'score' => '1-0',
        'resume' => 'Une victoire serrée pour Lens grâce à un but de Fofana à la 75e minute.',
        'is_active' => false,
    ],
    [
        'sport' => 'football',
        'equipe1' => ['name' => 'Rennes', 'color' => '#CE1126'],
        'equipe2' => ['name' => 'Nice', 'color' => '#ED1C24'],
        'score' => '0-3',
        'resume' => 'Nice a surpris Rennes avec une défense solide et trois contre-attaques fulgurantes.',
        'is_active' => true,
    ],
];
