services:
  # Création du service BDD
  mysql-blog:
    # Sous-dossier contenant le Dockerfile 
    build: ./db
    # Nom de l'image créée à partir du Dockerfile
    image: mysql-blog
    # Le nom du conteneur instancié
    container_name: mysql-blog
    restart: 'always'
    # Montage de volumes divers
    volumes:
      - ${LOG_DIR_MYSQL}:/var/log/mysql
      - ${MYSQL_DUMP_DIR}:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "9806:3306"

# Variable d'environnement utilisables :
# MYSQL_ROOT_PASSWORD
# MYSQL_DATABASE
# MYSQL_USER
# MYSQL_PASSWORD
# MYSQL_ALLOW_EMPTY_PASSWORD
# MYSQL_RANDOM_ROOT_PASSWORD
# MYSQL_ONETIME_PASSWORD